name: foxan
favicon: null
layout_spectrum: 0.02960580913349986
typography_spectrum: 0.9660162921063602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7887055126484483
  lightness: 0.1166287767700851
  saturation: 0.27062202454544604
  rhythmicContrast: 0.9735443710815161
purpose: []
